# Generated by Django 3.1.3 on 2021-01-20 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='ppr',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='recAvgYd',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='rushAvgYd',
            field=models.FloatField(null=True),
        ),
    ]
