# Generated by Django 3.1.3 on 2021-01-20 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210120_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='player',
            name='fumble',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='player',
            name='interception',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='player',
            name='posRank',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='player',
            name='rec',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='player',
            name='recTD',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='player',
            name='recYd',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='player',
            name='rushAtt',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='player',
            name='rushTD',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='player',
            name='rushYd',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='player',
            name='target',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='player',
            name='throwAtt',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='player',
            name='throwTD',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='player',
            name='throwYd',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='player',
            name='totGames',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='player',
            name='totalTD',
            field=models.IntegerField(),
        ),
    ]
