# Generated by Django 3.1.3 on 2021-02-14 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210120_0106'),
    ]

    operations = [
        migrations.CreateModel(
            name='DraftedPlayer',
            fields=[
                ('player_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.player')),
                ('pickedTeam', models.IntegerField(null=True)),
            ],
            bases=('api.player',),
        ),
    ]
