# Generated by Django 3.1.3 on 2021-02-16 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('position', models.CharField(max_length=2, null=True)),
                ('age', models.IntegerField(null=True)),
                ('posRank', models.IntegerField(null=True)),
                ('team', models.CharField(max_length=5)),
                ('throwAtt', models.IntegerField(null=True)),
                ('throwYd', models.IntegerField(null=True)),
                ('throwTD', models.IntegerField(null=True)),
                ('interception', models.IntegerField(null=True)),
                ('rushAtt', models.IntegerField(null=True)),
                ('rushYd', models.IntegerField(null=True)),
                ('rushTD', models.IntegerField(null=True)),
                ('rushAvgYd', models.FloatField(null=True)),
                ('target', models.IntegerField(null=True)),
                ('rec', models.IntegerField(null=True)),
                ('recYd', models.IntegerField(null=True)),
                ('recAvgYd', models.FloatField(null=True)),
                ('recTD', models.IntegerField(null=True)),
                ('totalTD', models.IntegerField(null=True)),
                ('fumble', models.IntegerField(null=True)),
                ('fpts', models.FloatField(null=True)),
                ('ppr', models.FloatField(null=True)),
                ('totGames', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DraftedPlayer',
            fields=[
                ('player_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='draftapi.player')),
                ('pickedTeam', models.IntegerField(null=True)),
            ],
            bases=('draftapi.player',),
        ),
    ]
